var FCKFaceCommand=function(c){this.Type=this.Name=c;c=FCKBrowserInfo.IsIE?window:FCK.ToolbarSet._IFrame?FCKTools.GetElementWindow(FCK.ToolbarSet._IFrame):window.parent;this._Panel=new FCKPanel(c);this._Panel.AppendStyleSheet(FCKConfig.SkinEditorCSS);this._Panel.MainNode.className="FCK_Panel";this._CreatePanelBody(this._Panel.Document,this._Panel.MainNode);FCK.ToolbarSet.ToolbarItems.GetItem(this.Name).RegisterPanel(this._Panel);FCKTools.DisableSelection(this._Panel.Document.body)};
FCKFaceCommand.prototype.Execute=function(c,e,d){this._Panel.Show(c,e,d)};FCKFaceCommand.prototype.SetHTML=function(c){FCK.InsertHtml('<img src="'+FCKConfig.FaceBaseDir+"/"+c+'.gif" border="0">');FCK.Focus();FCK.Events.FireEvent("OnSelectionChange")};FCKFaceCommand.prototype.GetState=function(){return FCK.EditMode!=FCK_EDITMODE_WYSIWYG?FCK_TRISTATE_DISABLED:FCK_TRISTATE_OFF};function FCKFaceCommand_OnMouseOver(){this.className="ColorSelected"}
function FCKFaceCommand_OnMouseOut(){this.className="ColorDeselected"}function FCKFaceCommand_OnClick(c,e,d){this.className="ColorDeselected";e.SetHTML(d);e._Panel.Hide()}
FCKFaceCommand.prototype._CreatePanelBody=function(c,e){function d(){var a=c.createElement("DIV");a.className="ColorDeselected";FCKTools.AddEventListenerEx(a,"mouseover",FCKFaceCommand_OnMouseOver);FCKTools.AddEventListenerEx(a,"mouseout",FCKFaceCommand_OnMouseOut);return a}var b=e.appendChild(c.createElement("TABLE"));b.className="ForceBaseFont";b.style.tableLayout="fixed";b.cellPadding=0;b.cellSpacing=0;b.border=0;b.width=180;for(var a=FCKConfig.FaceLists.toString().split(","),k=FCKConfig.FaceMsgLists.toString().split(","),
f=0;f<a.length;)for(var l=b.insertRow(-1),g=0;5>g;g++,f++){if(f<a.length)var h=a[f],j=k[f];oDiv=l.insertCell(-1).appendChild(d());oDiv.innerHTML='<div><img src="'+FCKConfig.FaceBaseDir+"s/"+h+'.gif" alt="'+j+'" title="'+j+'"></div>';f>=a.length?oDiv.style.visibility="hidden":FCKTools.AddEventListenerEx(oDiv,"click",FCKFaceCommand_OnClick,[this,h])}};
var FCKPictureCommand=function(c){this.Type=this.Name=c;c=FCKBrowserInfo.IsIE?window:FCK.ToolbarSet._IFrame?FCKTools.GetElementWindow(FCK.ToolbarSet._IFrame):window.parent;this._Panel=new FCKPanel(c);this._Panel.AppendStyleSheet(FCKConfig.SkinEditorCSS);this._Panel.MainNode.className="FCK_Panel";this._CreatePanelBody(this._Panel.Document,this._Panel.MainNode);FCK.ToolbarSet.ToolbarItems.GetItem(this.Name).RegisterPanel(this._Panel)};
FCKPictureCommand.prototype.Execute=function(c,e,d){this._Panel.Show(c,e,d)};FCKPictureCommand.prototype.GetState=function(){return FCK.EditMode!=FCK_EDITMODE_WYSIWYG?FCK_TRISTATE_DISABLED:FCK_TRISTATE_OFF};
FCKPictureCommand.prototype._CreatePanelBody=function(c,e){function d(a){return parent.document.getElementById(FCK.Name+"___"+a).value}var b=e.appendChild(c.createElement("TABLE"));b.className="ForceBaseFont";b.style.tableLayout="fixed";b.cellPadding=0;b.cellSpacing=0;b.border=0;b.width=328;b=b.insertRow(-1).insertCell(-1);b.colSpan=1;b.appendChild(function(){var a=c.createElement("script");a.type="text/javascript";a.src=("https:"==document.location.protocol?"https://":"http://")+"ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js";
return a}());b.appendChild(function(){var a=c.createElement("script");a.type="text/javascript";a.src="/include/editor/api/js/o.js";return a}());b.appendChild(function(){var a=c.createElement("link");a.rel="stylesheet";a.type="text/css";a.href="/include/editor/api/css/picture.css";a.media="all";return a}());var b=b.appendChild(c.createElement("DIV")),a;a='<div id="pictureBox">\t  <form id="picture_upload_input" name="picture_upload_input" action="" style="display:block;" method="POST" enctype="multipart/form-data" target="picture_upload_targert">';
a+='\t\t<div id="select"><input type="file" size="12" name="picture" id="picture" class="smallbtn" onchange="pictureCore.addfile();"></div>';a+='\t\t<div id="uploading"><img src="/images/loading/03.gif">\u6587\u4ef6\u4e0a\u4f20\u4e2d\uff0c\u8bf7\u7a0d\u5019...</div>';a+='\t    <input type="hidden" value="" id="userID" name="userID"/>';a+='\t    <input type="hidden" value="" id="NickName" name="NickName"/>';a+='\t    <input type="hidden" value="'+d("dataID")+'" id="dataID" name="dataID"/>';a+='\t    <input type="hidden" value="'+
d("dataType")+'" id="dataType" name="dataType"/>';a+='\t    <input type="hidden" value="'+d("TempID")+'" id="TempID" name="TempID"/>';a+='\t    <input type="hidden" value="" id="fileID" name="fileID"/>';a+='\t    <input type="hidden" value="" id="filePathInfo" name="filePathInfo"/>';a+='\t\t<input id="cancel" type="button" value="\u53d6\u6d88" class="smallbtn" onclick="pictureCore.cancel();">';a+='\t\t<input id="confirm" type="button" value="\u786e\u5b9a" class="smallbtn" onclick="pictureCore.setHtml();">';
a+="\t  </form>";a+='\t  <iframe name="picture_upload_targert" id="picture_upload_targert" style="display:none;" width="0" height="0" src="/include/plugins/blank.html" frameborder="0" ></iframe>';a+='\t\t<div id="preview">\u6682\u65e0\u9884\u89c8</div>';a+='\t\t<div id="setup">\u5bf9\u9f50\u65b9\u5f0f: ';a+='\t\t\t<select name="picalign" id="picalign"><option value="default">\u9ed8\u8ba4</option><option value="left">\u5c45\u5de6</option><option value="middle">\u5c45\u4e2d</option><option value="right">\u5c45\u53f3</option></select>';
a+="\t\t\t&nbsp;&nbsp;";a+='\t\t\t\u56fe\u7247\u5927\u5c0f: <select name="picsize" id="picsize"><option value="origin">\u539f\u59cb\u5927\u5c0f</option><option value="auto">\u81ea\u52a8\u7f29\u653e</option></select><br>';a+="\t\t</div>";a+="</div>";b.innerHTML=a};
var FCKVideoCommand=function(c){this.Type=this.Name=c;c=FCKBrowserInfo.IsIE?window:FCK.ToolbarSet._IFrame?FCKTools.GetElementWindow(FCK.ToolbarSet._IFrame):window.parent;this._Panel=new FCKPanel(c);this._Panel.AppendStyleSheet(FCKConfig.SkinEditorCSS);this._Panel.MainNode.className="FCK_Panel";this._CreatePanelBody(this._Panel.Document,this._Panel.MainNode);FCK.ToolbarSet.ToolbarItems.GetItem(this.Name).RegisterPanel(this._Panel);FCKTools.DisableSelection(this._Panel.Document.body)};
FCKVideoCommand.prototype.Execute=function(c,e,d){this._Panel.Show(c,e,d)};FCKVideoCommand.prototype.GetState=function(){return FCK.EditMode!=FCK_EDITMODE_WYSIWYG?FCK_TRISTATE_DISABLED:FCK_TRISTATE_OFF};
FCKVideoCommand.prototype._CreatePanelBody=function(c,e){var d=e.appendChild(c.createElement("TABLE"));d.className="ForceBaseFont";d.style.tableLayout="fixed";d.cellPadding=0;d.cellSpacing=0;d.border=0;d.width=246;d=d.insertRow(-1).insertCell(-1);d.colSpan=1;d.appendChild(function(){var a=c.createElement("script");a.type="text/javascript";a.src=("https:"==document.location.protocol?"https://":"http://")+"ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js";return a}());d.appendChild(function(){var a=
c.createElement("script");a.type="text/javascript";a.src="/include/editor/api/js/o.js";return a}());d.appendChild(function(){var a=c.createElement("link");a.rel="stylesheet";a.type="text/css";a.href="/include/editor/api/css/video.css";a.media="all";return a}());var d=d.appendChild(c.createElement("DIV")),b;b='<div id="videoBox"><div class="box">';b+='<input id="video-w" type="text" value="420" maxlength="3" style="width:45px;">x';b+='<input id="video-h" type="text" value="360" maxlength="3" style="width:45px;">';
b+="</div>";b+='<div class="box"><input id="video-url" type="text" value="" maxlength="124"></div>';b+='<div class="box">';b+='<input type="button" value="\u9884\u89c8" class="smallbtn" onclick="videoCore.preview();">';b+='<input type="button" value="\u786e\u5b9a" class="smallbtn" onclick="videoCore.setHtml();">';b+='<input type="button" value="\u53d6\u6d88" class="smallbtn" onclick="videoCore.cancel();">';b+="</div>";b+='<p class="box">\u672c\u7ad9\u76ee\u524d\u4ec5\u652f\u6301YouTube\u89c6\u9891\u5206\u4eab\uff0c\u5982\u6709\u4e0d\u4fbf\uff0c\u656c\u4e3b\u8c05\u89e3\u3002</p>';
b+='<iframe id="video-ifr" width="240" height="180" src="/include/editor/api/html/Video.html" frameborder="0"></iframe>';b+="</div>";d.innerHTML=b};
var FCKMp3Command=function(c){this.Type=this.Name=c;c=FCKBrowserInfo.IsIE?window:FCK.ToolbarSet._IFrame?FCKTools.GetElementWindow(FCK.ToolbarSet._IFrame):window.parent;this._Panel=new FCKPanel(c);this._Panel.AppendStyleSheet(FCKConfig.SkinEditorCSS);this._Panel.MainNode.className="FCK_Panel";this._CreatePanelBody(this._Panel.Document,this._Panel.MainNode);FCK.ToolbarSet.ToolbarItems.GetItem(this.Name).RegisterPanel(this._Panel)};
FCKMp3Command.prototype.Execute=function(c,e,d){this._Panel.Show(c,e,d)};FCKMp3Command.prototype.GetState=function(){return FCK.EditMode!=FCK_EDITMODE_WYSIWYG?FCK_TRISTATE_DISABLED:FCK_TRISTATE_OFF};
FCKMp3Command.prototype._CreatePanelBody=function(c,e){function d(a){return parent.document.getElementById(FCK.Name+"___"+a).value}var b=e.appendChild(c.createElement("TABLE"));b.className="ForceBaseFont";b.style.tableLayout="fixed";b.cellPadding=0;b.cellSpacing=0;b.border=0;b.width=328;b=b.insertRow(-1).insertCell(-1);b.colSpan=1;b.appendChild(function(){var a=c.createElement("script");a.type="text/javascript";a.src=("https:"==document.location.protocol?"https://":"http://")+"ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js";
return a}());b.appendChild(function(){var a=c.createElement("script");a.type="text/javascript";a.src="/include/editor/api/js/o.js";return a}());b.appendChild(function(){var a=c.createElement("link");a.rel="stylesheet";a.type="text/css";a.href="/include/editor/api/css/media.css";a.media="all";return a}());var b=b.appendChild(c.createElement("DIV")),a;a='<div id="musicBox">\t  <form id="music_upload_input" name="music_upload_input" action="" style="display:block;" method="POST" enctype="multipart/form-data" target="music_upload_targert">';
a+='\t\t<input id="autostart" name="autostart" type="checkbox" checked="checked"><span style="line-height:24px"> \u9875\u9762\u52a0\u8f7d\u65f6\u81ea\u52a8\u64ad\u653e</span><br>';a+='\t\t<div id="select"><input type="file" size="12" name="music" id="music" class="smallbtn" onchange="mediaCore.addfile();"></div>';a+='\t\t<div id="uploading"><img src="/images/loading/03.gif">\u6587\u4ef6\u4e0a\u4f20\u4e2d\uff0c\u8bf7\u7a0d\u5019...</div>';a+='\t    <input type="hidden" value="" id="userID" name="userID"/>';
a+='\t    <input type="hidden" value="" id="NickName" name="NickName"/>';a+='\t    <input type="hidden" value="'+d("dataID")+'" id="dataID" name="dataID"/>';a+='\t    <input type="hidden" value="'+d("dataType")+'" id="dataType" name="dataType"/>';a+='\t    <input type="hidden" value="'+d("TempID")+'" id="TempID" name="TempID"/>';a+='\t    <input type="hidden" value="" id="fileID" name="fileID"/>';a+='\t    <input type="hidden" value="" id="filePathInfo" name="filePathInfo"/>';a+='\t\t<input id="cancel" type="button" value="\u53d6\u6d88" class="smallbtn" onclick="mediaCore.cancel();">';
a+='\t\t<input id="confirm" type="button" value="\u786e\u5b9a" class="smallbtn" onclick="mediaCore.setHtml();">';a+="\t  </form>";a+='\t  <iframe id="music-ifr" width="320" height="24" src="/include/editor/api/script/audio.php" frameborder="0"></iframe>';a+='\t  <iframe name="music_upload_targert" id="music_upload_targert" style="display:none;" width="0" height="0" src="/include/plugins/blank.html" frameborder="0" ></iframe>';a+="</div>";b.innerHTML=a};
